name: 'setup-ci'
description: 'Sets up a toolchain on CI for building spatial-model-editor'
inputs:
  extra-deps:
    description: 'Additional dependencies to install'
    required: false
    default: ''
runs:
  using: "composite"
  steps:

    - if: runner.os == 'Linux'
      shell: bash
      run: |
        # set environment variables
        echo "INSTALL_PREFIX=/opt/smelibs" >> $GITHUB_ENV
        echo "SUDO_CMD=sudo" >> $GITHUB_ENV
        echo "TARGET_TRIPLE=x86_64-unknown-linux-gnu" >> $GITHUB_ENV
        echo "HOST_TRIPLE=x86_64-unknown-linux-gnu" >> $GITHUB_ENV

        echo "PYTHON_EXE=/usr/bin/python3" >> $GITHUB_ENV
        echo "OS=linux" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

        # add llvm repo for clang
        sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main"
        sudo apt update -yy

        # install clang, ninja, qt build deps, and any extra dependencies
        sudo apt install -yy clang-18 ninja-build libglu1-mesa-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxkbcommon-dev libxkbcommon-x11-dev '^libxcb.*-dev' ${{ inputs.extra-deps }}

        # set default clang version
        sudo update-alternatives --remove-all clang || echo "nothing to remove"
        sudo update-alternatives --remove-all clang++ || echo "nothing to remove"
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
        clang++ --version

        # disable system blas/lapack
        sudo rm /usr/lib/x86_64-linux-gnu/libblas*
        sudo rm /usr/lib/x86_64-linux-gnu/liblapack*

    - if: runner.os == 'macOS'
      shell: bash
      run: |
        # set environment variables
        echo "INSTALL_PREFIX=/opt/smelibs" >> $GITHUB_ENV
        echo "SUDO_CMD=sudo" >> $GITHUB_ENV
        echo "TARGET_TRIPLE=x86_64-apple-darwin16" >> $GITHUB_ENV
        echo "HOST_TRIPLE=x86_64-apple-darwin16" >> $GITHUB_ENV
        echo "PYTHON_EXE=/usr/bin/python3" >> $GITHUB_ENV
        echo "OS=osx" >> $GITHUB_ENV
        echo "MACOSX_DEPLOYMENT_TARGET=11" >> $GITHUB_ENV

        # install ninja, bison, flex and any extra dependencies
        brew install ninja bison flex ${{ inputs.extra-deps }}
        echo "/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH" > $GITHUB_PATH

    - if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "14.3"

    - if: runner.os == 'Windows'
      shell: bash
      run: |
        # set environment variables
        echo "INSTALL_PREFIX=/c/smelibs" >> $GITHUB_ENV
        echo "SUDO_CMD=" >> $GITHUB_ENV
        echo "TARGET_TRIPLE=x86_64-w64-windows-gnu" >> $GITHUB_ENV
        echo "HOST_TRIPLE=x86_64-w64-mingw64" >> $GITHUB_ENV
        echo "PYTHON_EXE=/ucrt64/bin/python" >> $GITHUB_ENV
        echo "OS=win64-mingw" >> $GITHUB_ENV
    - if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-python mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-git-lfs make m4 git dos2unix diffutils flex bison ${{ inputs.extra-deps }}

    # temporary install of cmake 3.29.2 due to dune cmake issue with 3.29.1 (msys already has 3.29.2)
    - if: runner.os != 'Windows'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: "3.29.2"
